#!/usr/bin/python

from opsgenie import OpsGenie
from opsgenie.config import Configuration
from opsgenie.swagger_client import AlertApi
from opsgenie.swagger_client.models import *
from opsgenie.swagger_client.rest import ApiException
import socket
import hashlib
import os
import time
import sys

API_KEY = "YOUR_API_KEY"

if API_KEY is "YOUR_API_KEY":
    print "Must specify API_KEY!"
    exit( 1 )

if len(sys.argv) == 1:
    print "%s <issue>", sys.argv[0]
    exit( 1 )

config = Configuration(apikey=API_KEY)
client = OpsGenie(config)

EVENT=sys.argv[1]
HOST=socket.gethostname()

m = hashlib.md5()
m.update( HOST + ":" + EVENT)

file = "/tmp/opsgenie-" + m.hexdigest()
if not os.path.isfile( file ):
    print "%s does not exist", file
    exit( 1 )

with open (file, "r") as myfile:
    IDENTIFIER=myfile.readlines()

print IDENTIFIER

body = CloseAlertRequest(
    note='Condition resolved')
try:
    response = AlertApi().close_alert(identifier=IDENTIFIER[0], identifier_type='id', body=body)


    print('request id: {}'.format(response.request_id))
    print('took: {}'.format(response.took))
    print('result: {}'.format(response.result))

    os.remove( file )
except ApiException as err:
    print("Exception when calling AlertApi->create_alert: %s\n" % err)
    exit( 1 )
